name: TypeScript Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm install
      
      - name: Run type check
        run: npm run lint
      
      - name: YAML lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: |
            .github/workflows/
            .pre-commit-config.yaml

      - name: Pre-commit check
        uses: pre-commit/action@v3.0.1
